name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
            python-version: '3.12'
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pelican content -o output -s pelicanconf.py
